#!/bin/bash

# Collect system information
HOSTNAME=$(hostname)
source /etc/os-release
OS="$NAME $VERSION"
UPTIME=$(uptime -p)

# Collect hardware information
CPU=$(lscpu | grep "Model name" | sed 's/Model name: *//')
RAM=$(free -h | grep Mem | awk '{print $2}')
DISK=$(lsblk -o NAME,SIZE,MODEL | grep disk)
VIDEO=$(lspci | grep VGA | awk '{print $4, $5, $6}')

# Collect network information
FQDN=$(hostname -f)
IP=$(ip a show eth0 | grep inet | awk '{print $2}')
GATEWAY=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(grep nameserver /etc/resolv.conf | awk '{print $2}')

# Collect system status
USERS_LOGGED=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',')
DISK_SPACE=$(df -h / | awk 'NR==2 {print $4}')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(cat /proc/loadavg | awk '{print $1, $2, $3}')
LISTENING_PORTS=$(ss -tuln | grep LISTEN | wc -l)
UFW_STATUS=$(ufw status | grep "Status:" | awk '{print $2}')

# Output the system report
echo ""
echo "System Report generated by $(whoami), $(date)"
echo ""
echo "System Information"
echo "------------------"
echo "Hostname: $HOSTNAME"
echo "OS: $OS"
echo "Uptime: $UPTIME"
echo ""
echo "Hardware Information"
echo "--------------------"
echo "CPU: $CPU"
echo "RAM: $RAM"
echo "Disk(s): $DISK"
echo "Video: $VIDEO"
echo ""
echo "Network Information"
echo "-------------------"
echo "FQDN: $FQDN"
echo "Host Address: $IP"
echo "Gateway IP: $GATEWAY"
echo "DNS Server: $DNS_SERVER"
echo ""
echo "System Status"
echo "-------------"
echo "Users Logged In: $USERS_LOGGED"
echo "Disk Space: $DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVERAGES"
echo "Listening Network Ports: $LISTENING_PORTS"
echo "UFW Status: $UFW_STATUS"
echo ""

